# Read about `build.yaml` at https://pub.dartlang.org/packages/build_config
builders:
  brickAdaptersBuilder:
    import: "package:brick_cloud_firestore_build/build_cloud_firestore.dart"
    builder_factories: ["cloudFirestoreAdaptersBuilder"]
    build_extensions: {".dart": [".adapter_build_cloud_firestore.dart"]}
    build_to: cache
    auto_apply: root_package
    applies_builders: ["source_gen|combining_builder"]
    defaults:
      generate_for:
        include:
          - lib/app/models/*.dart
          - app/models/*.dart
        exclude:
          - lib/app/adapters/*.dart
          - app/adapters/*.dart
          - lib/app/db/*.dart
          - app/db/*.dart

  brickModelDictionaryBuilder:
    import: "package:brick_cloud_firestore_build/build_cloud_firestore.dart"
    builder_factories: ["cloudFirestoreModelDictionaryBuilder"]
    build_extensions: {".brick_aggregate.dart": [".brick_aggregate.model_dictionary_build_cloud_firestore.dart"]}
    build_to: cache
    auto_apply: root_package
    applies_builders: ["source_gen|combining_builder"]
