name: brick_offline_first_with_cloud_firestore_build
description: Code generation library for Cloud Firestore

version: 0.0.1

environment:
  sdk: '>=2.4.0 <3.0.0'

dependencies:
  analyzer: ^0.39.0
  brick_build: any
  brick_sqlite_build:
    git:
      url: git@github.com:greenbits/brick.git
      path: packages/brick_sqlite_build
  brick_cloud_firestore_build:
    path: ../brick_cloud_firestore_build
  brick_cloud_firestore_abstract:
    path: ../brick_cloud_firestore_abstract

dev_dependencies:
  build_verify: ^1.1.0
  source_gen_test: ^0.1.0+6
  test: ">=1.9.4 <2.0.0"
