name: brick_cloud_firestore_build
description: Code generation library for Cloud Firestore

version: 0.0.1

environment:
  sdk: '>=2.4.0 <3.0.0'

dependencies:
  analyzer: ^0.39.0
  brick_build: any
  # brick_build:
  #   path: ../brick/packages/brick_build
  brick_cloud_firestore_abstract:
    path: ../brick_cloud_firestore_abstract
  build: ^1.2.0
  build_config: ^0.4.0
  dart_style: ^1.2.4
  glob: ^1.2.0
  meta: ^1.1.6
  path: ^1.6.3
  source_gen: ^0.9.0

dev_dependencies:
  build_verify: ^1.1.0
  source_gen_test: ^0.1.0+6
  test: ">=1.9.4 <2.0.0"
