name: brick_cloud_firestore
description: Cloud Firestore connector for Brick

version: 0.0.1

environment:
  sdk: '>=2.4.0 <3.0.0'
  flutter: '>=1.9.0 <2.0.0'

dependencies:
  brick_core: '>=0.0.1 <1.0.0'
  brick_cloud_firestore_abstract:
    path: '../brick_cloud_firestore_abstract'
  cloud_firestore: ^0.12.10+2
  flutter:
    sdk: flutter
  meta: '>=1.1.6 <2.0.0'

dev_dependencies:
  test: '>=1.9.4 <2.0.0'
  mockito: ^4.0.0
  flutter_test:
    sdk: flutter